pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'Yinglong'
include ':app'
include ':SoftEtherClient'
project(':SoftEtherClient').projectDir = file('third_party/SoftEtherClient')

include ':sstpClient'
project(':sstpClient').projectDir = file('third_party/sstpClient')
